### ISSUE TITLE
Lack of code style convention

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/depclean#38]
Currently, the DepClean codebase lacks proper code style conventions. This makes the codebase messy and is overall bad for maintainability. The best way to mitigate this is by enforcing the use of strict code style rules.

[Checkstyle](https://checkstyle.sourceforge.io/) is currently one of the best tools for this purpose. Configuring Checkstyle in DepClean will help newcomers to have a more clean codebase to work with.

**Comment by ABHAY0O7** [comment]
Hey... @cesarsotovalero,
I would like to work on this enhancement, may I?
And if yes then please also suggest to me some documentation of this repo, because if we use checkstyle for code style conventions then we have to also write incode short documentation of every method, class, and interface. So the documentation will help me a lot in understanding the codebase and also in writing short but effective incode documentation.

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, Welcome!

> I would like to work on this enhancement, may I?

I've already done it. But you can add documentation and fix Checkstyle warnings.

**Comment by ABHAY0O7** [comment]
Ya sure, I am on it.
