### ISSUE TITLE
DepClean Gradle plugin 

### ISSUE THREAD

**Issue by ABHAY0O7** [castor-software/depclean#67]
Hello @cesarsotovalero.
I was thinking of an idea to implement depclean-gradle-plugin and I have one for it.
The logic will be the same as what we used in the depclean-maven-plugin but in a Gradle project, we have to just convert the build.gradle file into its corresponding pom-default.xml and then we can use the gradle-maven plugin to analyze the dependencies and the project or we can just use it's code to analyze the dependencies in the name of gradle-plugin.
It is just an idea for now but I am thinking that sharing it with others either may improve it or may warn me that it has so many consequences.
So, anyone who sees this issue, please share your views on it.

Thank you
Abhay.

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7,
I’ve tried some tools before with the idea of Mavenizing existing projects, eg. [Mavenizer](www.soften.lu/site/OpenSource/Mavenizer), in order to apply DepClean directly and then report on the results. However, after some experiments, I realize that none of the tools that I tried produced a consistent POM file. The problem is that the Gradle build file is Groovy-based. This means that it relies on a flexible programming language that allows dynamic configs, instead of Maven that uses a more declarative and structured XML file. 

For the implementation of the Gradle plugin, I believe the best idea is to rely on [the Gradle API created for that purpose](https://docs.gradle.org/current/userguide/implementing_gradle_plugins.html) and reuse the logic of the `depclean-core` module as a dependency for the heavy duty bytecode analysis.

**Comment by ABHAY0O7** [comment]
Hi @cesarsotovalero, 
I got the point and failure or risks of what I had suggested earlier. And for now, as you suggested that the best idea is to rely on Gradle API for this purpose then we have to also consider that some developers still use kotlin as a build script for the Gradle build file so we have to also consider it while implementing this feature.

Thank you

**Comment by ABHAY0O7** [comment]
Hello @cesarsotovalero,
In recent days I had a tough time with covid but now it is all okay.
I want to show you some of my efforts in the implementation of the Gradle plugin.
I didn't create a PR for that as it is yet incomplete, but you can review my work [here](https://github.com/ABHAY0O7/depclean/tree/My_gradle) inside the `depclean-gradle-plugin` directory.
I only implemented (refactored) the core analysis classes that we can't use from the depclean core for the Gradle plugin.
The next steps will be to implement the plugin class and corresponding task class that will execute the depclean dependency analysis. These things can be done using [Gradle api](https://docs.gradle.org/current/javadoc/index.html).

Hoping this will be sufficient to show that I can complete this implementation during my GSoC period.
Waiting for your response...

Thank you
Abhay

**Comment by ABHAY0O7** [comment]
This feature has been implemented in 

- #94 
- #95
- #96 
- #97 
- #98 
- #99 
- #100 

Thank you
Abhay
