### ISSUE TITLE
[BUG] module-info 

### ISSUE THREAD

**Issue by imjhonny** [castor-software/depclean#90]
**Describe the bug**
Dependencies with _module-info_  appear as bloated, but it is indeed used. 

**To Reproduce**
For example in [Spork's visualization](https://castor-software.github.io/depclean-web/#/result/LD/spork/0111111111) the direct dependency junit-jupiter appears as bloated.  See also [Spoon's visualization ](https://castor-software.github.io/depclean-web/#/result/LD/spoon/0111111111)

**Expected behavior**
Dependencies with _module-info_  should appear as used.

**Comment by ABHAY0O7** [comment]
Hello @imjhonny 
This does not seem to be a bug for me, in fact, the [author](https://github.com/cesarsotovalero) uses a filter so that depClean didn't analyze classes like `module-info`, `package-info`, etc.
See [here](https://github.com/castor-software/depclean/blob/cbfc3954b429a124d92d18f125aac3daaf0b5f68/depclean-core/src/main/java/se/kth/depclean/core/analysis/ClassFileVisitorUtils.java#L91) in the code.
The logic behind this filter may be that since these types of classes only contain the general information of module, package, or project which I think rarely required a dependency or an artifact.
So, it will be better to ignore these classes(which may save time).

But if still, this seems to be a bug then it can be fixed easily.
@cesarsotovalero needs your opinion here.

Thank you
Abhay

**Comment by cesarsotovalero** [comment]
Hi @imjhonny, 

The viewpoint of @ABHAY0O7  is correct.

The dependency [`junit-jypiter`](https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter/5.5.2) is an aggregator of other JUnit dependencies. Aggregators are used to simplify the addition of many dependencies at once. In the case of this particular dependency, it contains a single `module-info.class` file, see also [here](https://github.com/junit-team/junit5/blob/main/junit-jupiter/src/module/org.junit.jupiter/module-info.java). 

Therefore, I  think it is correct for DepClean to report this type of dependencies as unused, and focus the analysis on the dependencies that actually contain executable bytecode, i.e., the sub-modules of `junit-jypiter.
